### ISSUE TITLE
Uncaught TypeError on startup

### ISSUE THREAD

**Issue by Ryan1729** [halohalospecial/atom-elmjutsu#11]
Since 2.50 I see the following error when starting up atom:

```
Uncaught TypeError: _this3.getWorkDirectory is not a function /home/ryan/.atom/packages/elmjutsu/lib/core.js:180
```

I would normally get the error repeated 2 or 3 times, but if I go to the indicated line and move the guard clause above the `setTimeout` call that tries to call `this.getWorkDirectory`, then I only get the error once.

**Comment by halohalospecial** [comment]
Hi @Ryan1729, thanks for the report!  Do you have `linter-elm-make` installed?

**Comment by halohalospecial** [comment]
My bad, I forgot to check if `linter-elm-make` is active in that part.  Should be fixed in the new release.

**Comment by Ryan1729** [comment]
That release stopped the errors. Thanks! 

For completeness' sake I'll mention that I did have `linter-elm-make` installed before, but I had uninstalled it before I started seeing the error.
