### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by kaskelotti** [halohalospecial/atom-elmjutsu#114]
[Enter steps to reproduce:]

1. Create an Elm source file that starts with multiline comment block `{- -}`
2. Use arrow keys to navigate back and forth the comment block

Using single line comments `--` works fine. Also, making any kind of syntax error on the source file seems to trigger this error.

**Atom**: 1.25.0 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.2.2

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At xxxx\.atom\packages\elmjutsu\lib\helper.js:249

TypeError: Cannot read property '1' of null
    at /packages/elmjutsu/lib/helper.js:249:44
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1097:15)
    at TextEditor.scanInBufferRange (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor.js:3378:73)
    at /packages/elmjutsu/lib/helper.js:241:16
    at Object.getActiveTopLevel (/packages/elmjutsu/lib/helper.js:254:31)
    at Object.sendActiveToken (/packages/elmjutsu/lib/indexing.js:89:14)
    at /packages/elmjutsu/lib/core.js:193:32
```

### Commands

```
  4x -1:58.6.0 core:move-down (input.hidden-input)
     -1:56.5.0 editor:consolidate-selections (input.hidden-input)
     -1:56.5.0 core:cancel (input.hidden-input)
  6x -1:56.1.0 core:move-down (input.hidden-input)
     -1:53.7.0 editor:consolidate-selections (input.hidden-input)
     -1:53.7.0 core:cancel (input.hidden-input)
  2x -1:52.7.0 core:move-down (input.hidden-input)
     -0:46.3.0 editor:consolidate-selections (input.hidden-input)
     -0:46.3.0 core:cancel (input.hidden-input)
     -0:45.5.0 core:move-down (input.hidden-input)
     -0:40.7.0 editor:consolidate-selections (input.hidden-input)
     -0:40.7.0 core:cancel (input.hidden-input)
     -0:39 intentions:highlight (input.hidden-input)
     -0:38.7.0 settings-view:open (input.hidden-input)
     -0:24.7.0 core:close (div.panels-item)
  2x -0:23.3.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
busy-signal 1.4.3 
cucumber 0.6.0 
elmjutsu 7.2.2 
highlight-selected 0.13.1 
intentions 1.1.5 
jshint 1.8.6 
language-asp 1.1.1 
language-elm 1.5.0 
language-sln 0.1.0 
language-vb 0.1.0-pre1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
project-manager 3.3.5 
```

**Comment by SidneyNemzer** [comment]
I'm also getting this error. Just started happening today. I've used elmjutsu in this project for a week and I haven't run into this. Possible related to the recent update to atom-ide-ui? That's the only change in my dev environment I can think of.

> Also, making any kind of syntax error on the source file seems to trigger this error.

That seems to be part of the cause. The multiline / single comment at top of the file... that would be a syntax error, right? Because the compiler is looking for a module definition? Maybe this error is not really related to comments, rather just any syntax errors?

**Comment by halohalospecial** [comment]
@kaskelotti, @SidneyNemzer, I could not replicate it :( Can you give me sample code? Thanks!

**Comment by kaskelotti** [comment]
Neither could I. I made a brand new elm file for this, but could not reproduce. My project file had this issue, but I cannot share that openly. After the latest elmjutsu update to version 7.2.6 the issues seems to be fixed.

I'll close this issue.
