### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by smucode** [halohalospecial/atom-elmjutsu#115]
I've had issues with atom performance working with elm for a while. Atom is just really slow, especially when switching tabs for instance. I tried to capture a performance log when switching tabs, and it seems like it's got to do with elmjutsu.

<img width="924" alt="screen shot 2018-04-06 at 15 14 22" src="https://user-images.githubusercontent.com/502358/38423231-9a6440c2-39ad-11e8-9b42-ae1fcc38ab99.png">

I've attached the performance if that helps:

[Profile-20180406T151438.json.zip](https://github.com/halohalospecial/atom-elmjutsu/files/1884090/Profile-20180406T151438.json.zip)

Not sure what i can do to debug this really.

**Comment by halohalospecial** [comment]
Hi @smucode, can you give me your Elmjutsu settings?

**Comment by smucode** [comment]
I have disabled everything but hyperclick.

**Comment by halohalospecial** [comment]
Have you tried it with just Elmjutsu installed?  (You can rename `~/.atom`, then restart Atom.)
Also, do you have lots of .elm files in the project or huge .elm files?

**Comment by smucode** [comment]
I still experience the problem with only elmjutsu, language-elm and atom-ide-ui. When i cmd+click a around, atom freezes and the profiles seems to indicate it's the indexer.

<img width="829" alt="screen shot 2018-04-07 at 11 23 40" src="https://user-images.githubusercontent.com/502358/38453462-9062cf18-3a56-11e8-87e8-8db9e80e141d.png">

With dependencies we have about 3.6k elm files.

**Comment by halohalospecial** [comment]
How many files do you have in your project (without dependencies)?  Was switching tabs still slow with just those packages installed?

**Comment by smucode** [comment]
About 200 files without dependencies. I haven't experienced slow tab switching, no. I'll update if I experience it again.

**Comment by halohalospecial** [comment]
Thanks!

As for Hyperclick/Go To Definition, there are cases where it will be slow (related to record fields, IIRC).  I'll look at it again when I have time :D

**Comment by smucode** [comment]
Yeah, i'm having all the same issues. Might be related to some other elm atom plugin i'm using (elm-format, elm-lens, linter-elm-make). Seems to be fairly OK when I restart atom, but after some use I notice ~3-5 second delays switching tabs, navigating the cursor around using the keyboard, selecting lines using the keyboard, and just general usage. The performance profiler always seems to be hinting towards the elmjutsu indexer. When I disable elmjutsu the lag goes away.

**Comment by halohalospecial** [comment]
If it's not much of a hassle, can you give a screen capture (like a gif or video)?  There might something that's not obvious.  You can also send me a direct message on Elm Slack (same username).  Thanks!

**Comment by halohalospecial** [comment]
As discussed on Slack, this is related to the Hyperclick support.  The workaround is to uncheck `Enable Hyperclick` for now.  A fix will be available in the next release.

**Comment by halohalospecial** [comment]
This should be fixed in the latest version (v.8.0.0).  Thanks to @smucode for the help in debugging!
