### ISSUE TITLE
 use of teletype broken when elmjutsu is enabled

### ISSUE THREAD

**Issue by dbj** [halohalospecial/atom-elmjutsu#118]
I'm running teletype 0.13.1, Atom 1.26.1, and elmjutsu 8.1.0. When I share a teletype session with another Atom user, and I bring up an Elm file for editing, the user's Atom editor freezes, though mine does not. If we edit other types of files, such as JS files, no problem, but as soon as we bring up an Elm file... freeze on the user's side.

This does not occur when I turn off elmjutsu. I have tried disabling and/or reinstalling teletype, elmjutsu, and other related packages, and nothing seems to fix this issue.

Also note, the same thing happens with linter-elm-make 0.28.3.

**Comment by halohalospecial** [comment]
Can you check if there are errors in the console?  Also, are you getting a "Failed to join portal" notification?

**Comment by halohalospecial** [comment]
Hi @dbj, can you check if the latest version (v8.1.1) works for you?  Thanks!

**Comment by dbj** [comment]
That fixed it!  Thanks. 😄
