### ISSUE TITLE
Atom Freezes when typing a space after a set of curly braces

### ISSUE THREAD

**Issue by SidneyNemzer** [halohalospecial/atom-elmjutsu#119]
## MCVE

1. Create a new Elm file, for example `Test.elm`.
2. Inside the the file, write the following:

```
a {}<space>
```
Upon typing the \<space\>, Atom freezes.

`a` is arbitrary -- it's the name of a declaration in this context, but the freeze occurs with any name as far as I can tell. Adding keys to the record is possible, but Atom still freezes after typing the space after the destructuring.

The curly braces seem to cause the problem; `a<space>...` does not freeze Atom.

## Notes

* This might be related to #54 
* Since I suspected a "too much recursion" problem, I opened the Atom devtools before triggering the freeze to watch for an error. But after about 5 minutes, Atom was still frozen (and no error in the console). Maybe it's not infinite recursion, or at least V8 doesn't think so.
* Atom will detect the editor is frozen after a minute or two and ask if you want to force close the editor
* Also occurs in type signatures: `a : {}<space>` (freezes at the \<space\>)
* Doesn't seem to occur outside of type signatures or declarations. Typing `{}<space>` in an otherwise empty file doesn't cause a problem

**Comment by SidneyNemzer** [comment]
Update: this also occurs with tuples:

`a ()<space>` causes a freeze

**Comment by halohalospecial** [comment]
@SidneyNemzer, this is indeed a bug.  You can uncheck `Enable Signature Help` in the meantime if you keep on running into this.  I'm checking it right now.  Thanks!

**Comment by halohalospecial** [comment]
@SidneyNemzer, can you try the latest version (v8.1.3) with `Enable Signature Help` checked?  Thanks!

**Comment by SidneyNemzer** [comment]
I also found that parentises that don't denote a tuple still cause a freeze:

```
a = (b >> c)<space> -- Freeze
```

**Comment by halohalospecial** [comment]
@SidneyNemzer, how about now?

**Comment by SidneyNemzer** [comment]
Seems to be fixed now. Thanks for the quick responses!

**Comment by halohalospecial** [comment]
Thank you too!
