### ISSUE TITLE
Elmjutsu won't load when seti-ui theme is used

### ISSUE THREAD

**Issue by otijhuis** [halohalospecial/atom-elmjutsu#12]
It looks like the less variable @text-color-added isn't working with the seti-ui theme. This isn't a elmjutsu problem, it works fine with other themes. Wanted to inform you in case you get reports of the latest version not working since the seti-ui theme is pretty popular.

**Comment by halohalospecial** [comment]
@otijhuis Thank you very much for this!  Turns out this is a critical issue since not all themes support `@text-color-added`.  Fixed in v2.5.5.
