### ISSUE TITLE
Uncaught Error: Trying to send an unexpected type of value through port `projectDependenciesChang...

### ISSUE THREAD

**Issue by CharlonTank** [halohalospecial/atom-elmjutsu#121]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 8.2.0

### Stack Trace

Uncaught Error: Trying to send an unexpected type of value through port `projectDependenciesChangedSub`:
Expecting a String at _[1][1][1] but instead got: {"elm/parser":"1.0.0","elm/regex":"1.0.0","elm/virtual-dom":"1.0.0","elm-community/dict-extra":"2.3.1","toastal/either":"4.0.0"}

```
At /Users/charlon/.atom/packages/elmjutsu/elm/indexer.js:2848

Error: Trying to send an unexpected type of value through port `projectDependenciesChangedSub`:
Expecting a String at _[1][1][1] but instead got: {"elm/parser":"1.0.0","elm/regex":"1.0.0","elm/virtual-dom":"1.0.0","elm-community/dict-extra":"2.3.1","toastal/either":"4.0.0"}
    at Object.send (/packages/elmjutsu/elm/indexer.js:2848:10)
    at /packages/elmjutsu/lib/indexer-worker.js:19:45)
    at Object.sendProjectDependencies (/packages/elmjutsu/lib/indexing.js:225:15)
    at /packages/elmjutsu/lib/core.js:362:16
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
elm-format 3.0.0 
elm-instant 2.0.0 
elm-lens 0.3.0 
elmjutsu 8.2.0 
hyperclick 0.1.5 
intentions 1.1.5 
language-elm 1.5.0 
language-haml 0.31.1 
linter 2.2.0 
linter-elm-make 0.28.5 
linter-haml 2.0.2 
linter-js-standard 5.1.0 
linter-ui-default 1.7.1 
rubocop-auto-correct 1.5.1 
```

**Comment by halohalospecial** [comment]
Hi!  Do you have a way to reproduce this?  Thanks!

**Comment by MethodGrab** [comment]
I get this error when first loading an Elm 0.19 project.
