### ISSUE TITLE
Autocomplete does not seem to work under the tests directory.

### ISSUE THREAD

**Issue by ababup1192** [halohalospecial/atom-elmjutsu#130]
Hi

Autocomplete for dependencies packages does not work in tests directory.

![2018-09-03 16 47 46](https://user-images.githubusercontent.com/1853727/44975744-31ccd080-af9e-11e8-84d5-40afce59f370.png)

elm.json
```
{
    "type": "application",
    "source-directories": [
        "src",
        "tests"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.0",
            "elm/core": "1.0.0",
            "elm/html": "1.0.0",
            "elm/random": "1.0.0"
        },
        "indirect": {
            "elm/json": "1.0.0",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "elm/virtual-dom": "1.0.0"
        }
    },
    "test-dependencies": {
        "direct": {
            "elm-explorations/test": "1.0.0"
        },
        "indirect": {}
    }
}
```

This is my [repository](https://github.com/ababup1192/elm-dev-env) for development.

I use Elm 0.19 and elmjutsu 8.5.0.

**Comment by halohalospecial** [comment]
Hi @ababup1192, can you check v8.6.1?  Thanks for the screenshot and sample project!

**Comment by ababup1192** [comment]
Hi @halohalospecial, Thank you very much for updating!  Autocomplete has been effective successfully.

However, why continue to keep this error?

![2018-09-03 23 37 18](https://user-images.githubusercontent.com/1853727/44992578-973ab480-afd2-11e8-8fc2-6ba39b599b2f.png)

**Comment by halohalospecial** [comment]
Hi @ababup1192, saving `Tests.elm` runs `elm make tests/Tests.elm` (the active file).  You can enable the `Always Compile Main` option so that Elmjutsu always runs `elm make src/Main.elm` instead.

https://github.com/halohalospecial/atom-elmjutsu#always-compile-main

**Comment by ababup1192** [comment]
Great! The error has been resolved!
