### ISSUE TITLE
Autocomplete without automating inserting of default arguments

### ISSUE THREAD

**Issue by ghivert** [halohalospecial/atom-elmjutsu#132]
Hi!

Today, when autocompleting a function waiting for arguments, the autocomplete automatically inserts default arguments according to the function signature. But, in a lot of cases (when dealing with currying) I don't want them to be inserted. Moreover, if this behavior is specifically desired, there's the `Insert Default Arguments` features.

Is there any way to deactivate it?

**Comment by halohalospecial** [comment]
Hi @ghivert, you can go to the [Settings view](https://flight-manual.atom.io/getting-started/sections/atom-basics/#settings-and-preferences) to disable that.

**Comment by ghivert** [comment]
To be honest, I can't find the option, neither in the Core Settings View nor the autocomplete-plus package settings... 🙁

**Comment by halohalospecial** [comment]
It's an Elmjutsu setting :)

![elmjutsu-settings](https://user-images.githubusercontent.com/2138906/45946259-fe241a00-c022-11e8-9a99-535a947fd591.png)
