### ISSUE TITLE
Allow auto-importing deep module names.

### ISSUE THREAD

**Issue by anagrius** [halohalospecial/atom-elmjutsu#134]
We have a large project. In order to keep things organised we use nested module names like:

```elm
module Humio.Ui.TimeSelector exposing (..)
```

 It would be great if Elmjutsu would support suggestions for importing them like it does top level modules.

In other words, today, elmjutsu suggests I import `TimeSelector` if I try to write:

```elm
div [ ] [ TimeSelector.view ]
```

and have not imported `Humio.Ui.Timeselector` yet. This is not what we want and leaves the auto-import feature almost useless. In this case it would add an import like:

```elm
import TimeSelector
``` 

and what we would like it to suggest is:

```elm
import Humio.Ui.TimeSelector as TimeSelector
```

**Comment by anagrius** [comment]
I don't see any change unfortunately.

We have two modules called `Confirm`, in two different parts of the codebase. I tried to say:

```elm
div [] [ Confirm.view ]
```
and wanted suggestions:

```elm
import Humio.View.Confirm.Confirm as Confirm
import Humio.Ui.Confirm as Confirm
```

but instead got:

<img width="515" alt="screenshot 2018-11-19 at 09 57 03" src="https://user-images.githubusercontent.com/157210/48696319-e495ed80-ebe1-11e8-82e9-9c751b4f428c.png">

So just like previous versions.

**Comment by anagrius** [comment]
Ah! I found it.

<img width="705" alt="screenshot 2018-11-19 at 10 01 51" src="https://user-images.githubusercontent.com/157210/48696429-30489700-ebe2-11e8-922f-c506136129a6.png">

**Comment by anagrius** [comment]
Yet it would be very nifty if it would suggest it in the error bubble, since that is usually where I notice it missing.

**Comment by anagrius** [comment]
Maybe have a single entry for "Import As" and the show the dialog above.

Or maybe I am not seeing it because we are still stuck with linter-elm-make?

**Comment by halohalospecial** [comment]
Ah, you want it to appear in the quick fix list?  Ok, I'll add that :)

**Comment by halohalospecial** [comment]
@anagrius, can you try v9.6.0?  Thanks!

**Comment by halohalospecial** [comment]
Oh, sorry.  It will work with Elm 0.19 projects.

**Comment by anagrius** [comment]
We will get there eventually :( But this is still very useful for us as-is. Thanks!

**Comment by halohalospecial** [comment]
@anagrius, can you try the following versions:

elmjutsu v9.7.0
linter-elm-make v0.29.0

**Comment by anagrius** [comment]
You sir, are a god! Works like a charm
