### ISSUE TITLE
"source-directories" are no longer part of `elm.json` for "type: package"

### ISSUE THREAD

**Issue by ymtszw** [halohalospecial/atom-elmjutsu#139]
When "Always compile main" option enabled, elmjutsu checks if paths specified in `elmjutsu-config.json` are actually in "source-directories".

This is OK for "type: application" project, however in "type: package" project, it looks like ["source-directories" are no longer part of `elm.json`](https://github.com/elm/compiler/blob/master/docs/elm.json/package.md).

We CAN manually introduce "source-directories" in `elm.json` for package project and it has no harm, though when you perform compiler commands that may update `elm.json` such as `elm bump`, the compiler actually erases "source-directories" entry from `elm.json`. Leads to additional manual fix.

So I propose:
- For package projects, entirely remove requirement of "main paths" coming with "Always compile main" option, since we can just `elm make` in such projects and compiler automatically resolves entry file (i.e. main paths) from "exposed-modules".
    - If we are making this change, better update help texts in settings view.
- For per-file compilation, no changes needed.

**Comment by halohalospecial** [comment]
Thanks!
