### ISSUE TITLE
How do I correctly specify a relative Elm Path?

### ISSUE THREAD

**Issue by mrattner** [halohalospecial/atom-elmjutsu#141]
In elmjutsu config, my value for Elm Path is `node_modules/.bin/elm`. When I run the linter in an Elm file, I get "Error parsing output. Please check the value of `Elm Path` and/or `Elm Test Path` in the Settings view."

Looking at the Atom debugger, I see that the Elm executable's full path is expanded correctly to `/home/marcy/elm-project/node_modules/.bin/elm`, but the spawned process exits with code 127 (command not found). When I recreate the command myself from within the same working directory, in my system terminal:

    ~/elm-project$  /home/marcy/elm-project/node_modules/.bin/elm make --report=json --output=/dev/null /home/marcy/elm-project/src/Main.elm

the Elm compiler executes successfully. Any advice?

**Comment by halohalospecial** [comment]
Hi!  Can you check the value of `executablePath` and `projectDirectory` at line 111?

https://github.com/halohalospecial/atom-elmjutsu/blob/4d5e2055ccf164f51b3df17d6f7f90c00642d510/lib/elm-make-runner.js#L108-L118

Thanks!

**Comment by gampleman** [comment]
I'm getting the same error. In my case:

`executablePath` is `/Users/gampleman/Programming/fmap/project/client/node_modules/.bin/elm` which seems correct.

`args` is `["make", "--report=json", "--output=/dev/null", "/Users/gampleman/Programming/fmap/project/client/src/Main.elm"]` 

`projectDirectory` is `/Users/gampleman/Programming/fmap/project/client`

**Comment by halohalospecial** [comment]
@gampleman, @mrattner, can you try uncommenting `// env: process.env, `?  Thanks!

**Comment by gampleman** [comment]
Sure.

After the promise resolves,
`data.stderr` is "env: node: No such file or directory"

**Comment by mrattner** [comment]
I haven't had the time to dig into this error, so thanks @gampleman for providing more info. That "node: No such file or directory" error you're seeing reminds me of a problem I've run into a couple of times, because of how the Node binary is named in some package managers (`nodejs` vs `node`--see [this stackoverflow post](https://stackoverflow.com/a/14914716) for more info). Even though I installed Node via [n-install](https://github.com/mklement0/n-install), I had to create a symlink from `node` to `nodejs` after I upgraded my Linux distro. Maybe that's related to this problem?

**Comment by halohalospecial** [comment]
@gampleman, @mrattner, I created a branch (`sb-exec-local`) that uses the `local` option of `sb-exec` when the `Elm Path` is `node_modules/.bin/elm`.  Not sure if it will make any difference since I didn't encounter compile issues without it :)

https://github.com/halohalospecial/atom-elmjutsu/blob/8069f0a075cc64dbc8e6fad6d1d09d89bbb79b0f/lib/elm-make-runner.js#L130-L145

**Comment by halohalospecial** [comment]
Did it work @mrattner ? :slightly_smiling_face:

**Comment by mrattner** [comment]
Yes, it worked! thanks! :tada:

**Comment by halohalospecial** [comment]
The changes are in v9.9.3.  Thanks!
