### ISSUE TITLE
Go to definition: not working on Mac OS

### ISSUE THREAD

**Issue by abhinavzspace** [halohalospecial/atom-elmjutsu#15]
I have looked at all the editors available with almost all the popular plugins available. I think you got the best.

Only thing is, in my setup "Go to definition" functionality is not working.

I have even deleted `.atom` directory which contains everything atom and downloaded fresh atom executable from their website. Then I installed language `language-elm`, `elmjutsu` and `hyperclick`. This is on Mac OS.

I am never able to go to definitions defined inside elm packages. But in one of the project structure I was able to go to definitions defined inside the same file and the files in the same folder.

Let me know if you need any more details.

If this gets fixed, it would be awesome. :)

**Comment by halohalospecial** [comment]
Right now, `Go To Definition` to 3rd-party packages is not yet implemented :-)

**Comment by abhinavzspace** [comment]
Oh. I hope you are on it. I am using it anyways :-).

**Comment by halohalospecial** [comment]
Hi @abhinavzspace, I'm still thinking about this :-)  Do you always need to go to the definition of 3rd-party package symbols?  It's not that hard to implement, but it will require the package to parse more files.  If you really need this, I may add it as an toggleable option instead.  Cheers!

**Comment by abhinavzspace** [comment]
It would be a great feature for someone like me at least, being used to going to source in webstorm/intellij. But If majority of the users have not encountered the need for this feature, I guess its not important and can wait. It's all up to you. :-)

**Comment by OvermindDL1** [comment]
I would like going to third-party packages as well as their usage is not always clear from their type and comments.  >.>

/me often has github up on a lot of third-party projects.

**Comment by halohalospecial** [comment]
Already working on this :-)

**Comment by halohalospecial** [comment]
Added in v2.6.0
