### ISSUE TITLE
Error notification 'Could not find elm-package.json'

### ISSUE THREAD

**Issue by raffomania** [halohalospecial/atom-elmjutsu#18]
This notification pops up every time I start atom in a non-elm project. Is there a way to make it less obtrusive?

**Comment by halohalospecial** [comment]
Hi @raffomania, that notification should only appear if you have an open `.elm` file :-)

**Comment by raffomania** [comment]
Interesting. It happens to me even in an empty folder. Any hints to debug this?

**Comment by halohalospecial** [comment]
Hmm, that's weird.  Can you provide a screen capture so that I can see your workflow?

**Comment by raffomania** [comment]
[Here you go](https://gfycat.com/DimpledPiercingJavalina). It's a pretty standard setup. Atom and all packages are up to date.

**Comment by halohalospecial** [comment]
Thank you for the screen cap.  That sure is weird!  Maybe another installed package has a bad interaction with elmjutsu (happened more than once before).

To be sure, you can do the following:

1. Quit Atom.
2. Rename `~/.atom` (e.g. `mv ~/.atom ~/.atom-backup`).
3. Open Atom.  Atom will create a new `~/.atom` directory.
4. Install `language-elm` and `elmjutsu`.
5. Quit Atom.
6. Open again Atom to check if the issue is still there.
7. If the issue has been resolved, you can install packages one by one to find out which has a bad interaction with elmjutsu.

P.S. I'm also usually online on <https://elmlang.slack.com> :-)

**Comment by halohalospecial** [comment]
@raffomania Not sure if you had this resolved already.  If not, you can try the latest version (2.8.4).  I fixed something that might be related to your issue.

**Comment by raffomania** [comment]
Wow, seems to be fixed with the latest version. Thanks a lot for this awesome plugin!

**Comment by amitaibu** [comment]
I've just updated to `7.1.5` and I experience this error whenever I open my project in a subdirectory (i.e. the `elm-package.json` is not present in the project).

If it's included, elmjitsu seems to work fine.

**Comment by halohalospecial** [comment]
How does the directory structure look like?

**Comment by amitaibu** [comment]
```
client (is the root, has `elm-package.json`)
    |_ src
       |_elm (this is where I open Atom)
           |_ App
           |_ Backend
           |_ Pages
       |_assets
       |_js
```

**Comment by halohalospecial** [comment]
The `elm` directory is the Atom project?  Can you try opening `client` as the Atom project instead?

**Comment by amitaibu** [comment]
Yes, if I open the `client` it works ok -- but up until the recent update (it was `7.1.2` if I'm not mistaken) it worked also by opening the `elm` directory.

**Comment by halohalospecial** [comment]
Yeah, sorry, it was to prevent it from going beyond the project directory when an `elm-package.json` doesn't exist.  (See https://github.com/halohalospecial/atom-elmjutsu/issues/24.)  Maybe there's a better way?

**Comment by amitaibu** [comment]
Just to clarify -- it seems #24 was solved long time ago (and it worked fine until my update today)

**Comment by halohalospecial** [comment]
Hmm.. maybe better to revert to the old behavior :)  I'll include the fix in the next release.  Thanks!
