### ISSUE TITLE
Go to definition freezing atom

### ISSUE THREAD

**Issue by chalmagean** [halohalospecial/atom-elmjutsu#19]
I've just tried "Go to definition" on a custom function and Atom just sits there unusable with my CPU at 100%. After asking me 2 times to Wait or Close, I had to hit close in order to continue my work.

I am using Atom 1.10.2 on OSX El Capitan

**Comment by chalmagean** [comment]
Oh scratch that, I had to "Go to declaration" options. The one causing the issue came from the "goto" package.

**Comment by halohalospecial** [comment]
This also happened to me before.  IIRC, only `Goto: File Symbol` worked properly.
