### ISSUE TITLE
Feature: Autocomplete function from type definition

### ISSUE THREAD

**Issue by brasilikum** [halohalospecial/atom-elmjutsu#2]
``` elm
add : Int -> Model -> Model
```

could suggest

``` elm
add : Int -> Model -> Model
add int model = 
```

What do you think?

**Comment by halohalospecial** [comment]
Hi @brasilikum, how will this work?  Is it a new command or part of autocomplete?  Let's say the cursor is at the end of `add : Int -> Model -> Model`, it will suggest `add int model =`?  I'm planning to do auto complete next and this seems useful!
