### ISSUE TITLE
end of line comments get moved to the next line

### ISSUE THREAD

**Issue by mojo2go** [halohalospecial/atom-elmjutsu#25]
I tend to use end-of-line comments.  Elmjutsu does not.  It moves them to the next line for me.
Can I tweak that behaviour?  How or where?  

What I want

```
    [ { name = "Mina", isComplete = False, id = 1 }
    , { name = "Joe", isComplete = True, id = 2 }   -- the test record
    ]
```

What Elmjutsu gives me

```
    [ { name = "Mina", isComplete = False, id = 1 }
    , { name = "Joe", isComplete = True, id = 2 }
      -- the test record
    ]
```

**Comment by halohalospecial** [comment]
Hi @mojo2go, you should submit this issue to https://github.com/avh4/elm-format instead :)

**Comment by OvermindDL1** [comment]
Entirely an elm-format issue as elm-format is what does that.  Also, you should use elm inline comment syntax instead of elm line comment syntax for in-expression comments like that, that is why elm-format moved it to a new line.
