### ISSUE TITLE
find usages doubled?

### ISSUE THREAD

**Issue by refried** [halohalospecial/atom-elmjutsu#26]
I'm seeing an issue where all of the results of Packages -> Elmjutsu -> Find Usages are doubled in the results pane.  e.g.

File 1 Usage 1
File 1 Usage 2
File 1 Usage 1
File 1 Usage 2
File 2 Usage 1
File 2 Usage 1

Can you think of any reason this might be happening?  Would another plugin interfere?

Thanks.

**Comment by halohalospecial** [comment]
Hi @refried can you provide a sample .elm file or project I can use to reproduce this?  Thanks!

**Comment by halohalospecial** [comment]
I think this is related to #81 :smile_cat:
