### ISSUE TITLE
failed to download package docs

### ISSUE THREAD

**Issue by feldman4** [halohalospecial/atom-elmjutsu#29]
After updating, sidekick is not working for public packages. Sidekick still works for local functions. Uninstall + reinstall of the package and changing the cache directory did nothing.

**Comment by feldman4** [comment]
Traced it back to a dependency in elm-package.json that isn't on http://package.elm-lang.org/ (contains Native code). It looks like failing to find that package's documentation caused all the other ones to fail.

**Comment by halohalospecial** [comment]
Hi @feldman4, I think your hunch is correct.  Right now, elmjutsu is using `Task.sequence` for that part.  Thanks for reporting this issue!
