### ISSUE TITLE
port to Visual Studio Code

### ISSUE THREAD

**Issue by AntouanK** [halohalospecial/atom-elmjutsu#34]
Any chance of this plugin ported to Visual Studio Code?

**Comment by halohalospecial** [comment]
Hi @AntouanK I haven't tried creating a VSCode extension yet, so I don't know how difficult it would be :grin: There were also others who wanted it to work with Sublime Text and Vim.  The code is kinda hackish and a bit coupled to Atom features right now, so the first step is to refactor the code to make it easier to work with other editors.  A part of me though wants to wait for the AST instead and reimplement the features with that :smile_cat:

**Comment by AntouanK** [comment]
I haven't worked on any plugin, so I don't know how difficult it is. 
If you do start some work to abstract it though, I can dig into VScode to see what we can do.

**Comment by halohalospecial** [comment]
I'll see what I can do if I get free time (no promises :grinning:).  Which features are you most interested in?

**Comment by AntouanK** [comment]
I don't use Atom, so I haven't use the plugin before.
It sure looks good though.
I guess I want to some basic autocomplete, mostly to see types , and the "go to".

but whatever you think it's easiest for starters.

**Comment by gyzerok** [comment]
I would like to vote for having it under VSCode as well. The work you've done for this plugin is really awesome 👍 ! And it is kind of forcing me to switch to Atom just because of your plugin. However I'd really enjoy being able to stay with VSCode while using it! :)

**Comment by aravantv** [comment]
Also +1

**Comment by halohalospecial** [comment]
Hi all!  I think it's better to collaborate on a language server instead (https://github.com/Microsoft/language-server-protocol) so that all editors can benefit :smile:

**Comment by aravantv** [comment]
True! Is there such an initiative for elm?

**Comment by jwoudenberg** [comment]
Hey there. I really like these tools and would love to help making them available in more editors. Specifically I'd like to port it to Vim, but I think it makes a ton of sense to collaborate on separating the tools from the many possible editor-specific wrappings.

**Comment by halohalospecial** [comment]
There's relevant discussion here: https://groups.google.com/forum/#!topic/elm-dev/aDWFBg72Wt4
