### ISSUE TITLE
Multiple elm-package.json files

### ISSUE THREAD

**Issue by pauldijou** [halohalospecial/atom-elmjutsu#35]
This plugin looks awesome but it crashes when I try to use it. The reason is that my project does not have a `elm-package.json` at the root of the folder. That's because I have two Elm projects, one for server-side, one for client-side, and some common source code.

```
├── client
│   ├── [some Elm code]
│   └── elm-package.json 
├── server
│   ├── [some Elm code]
│   └── elm-package.json 
└── src
    └──  [some common Elm code]
```

Is there any chance for the plugin to search for `elm-package.json` files inside subdirectories and support several Elm projects at once? Maybe with some ignored folders (either based on .gitignore or from plugin settings)

**Comment by halohalospecial** [comment]
Hi, what did you mean by "it crashes"?  Were there error notifications or console errors?

**Comment by pauldijou** [comment]
This is what I get right after enabling elmjutsu on my project (atom is opened at the root of the folder, not inside `client` nor `server`). Using 2.10.1, I'm having some internet issues and failed to update to last version. Will try again tomorrow.

![image](https://cloud.githubusercontent.com/assets/1275293/21701717/a5f7e988-d3a7-11e6-93fd-e5951fa4ab15.png)

**Comment by halohalospecial** [comment]
Ah, I see.  Did you open a `.elm` file in the `src` directory (which does not have an `elm-package.json`)?  When you open a `.elm` file, Elmjutsu will search for an `elm-package.json` in that directory or the parent directories.   Elmjutsu will treat the directory (where `elm-package.json` was found) as the "project directory" and needs to read `elm-package.json` for info about imports and such.  I don't know how to solve this elegantly right now :disappointed: Suggestions are welcome!

**Comment by pauldijou** [comment]
Yeah, you're right... I can see a way to do that either. So I tried to create a "fake" `elm-package.json` at the root of the project with all dependencies from both `client` and `server` but I got [a new error](https://github.com/halohalospecial/atom-elmjutsu/issues/39).

**Comment by halohalospecial** [comment]
Hi, do you have a sample project that I can use to replicate the issue?

**Comment by halohalospecial** [comment]
Hi, does the new directory structure look like this?

```
├── client
│   └── [some Elm code]
├── server
│   └── [some Elm code]
└── src
    └──  [some common Elm code]
└── elm-package.json
```

**Comment by pauldijou** [comment]
Yes, exactly. I will try to do the sample project this weekend.

Le 19 janv. 2017 8:47 AM, "halohalospecial" <notifications@github.com> a
écrit :

Hi, does the new directory structure look like this?

├── client
│   └── [some Elm code]
├── server
│   └── [some Elm code]
└── src
    └──  [some common Elm code]
└── elm-package.json

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/halohalospecial/atom-elmjutsu/issues/35#issuecomment-273703829>,
or mute the thread

**Comment by pauldijou** [comment]
Doing the sample project, I realized I had a wrong configuration in the project (one wrong `source-directories` in the `elm-package.json`). Fixing it fixed the Atom error.

There is only one thing that's not working but that's ok because I don't see any way how it could. It's the autocompletion when both `client` and `server` have the same module inside their respective folders exposing the same API (for example, a logger implementation) which is imported inside the common Elm code. Using the top level `elm-package.json`, there is no way to know which one is used.

Thanks again for the plugin!
