### ISSUE TITLE
Feature Request: Function is exposed indicator

### ISSUE THREAD

**Issue by OvermindDL1** [halohalospecial/atom-elmjutsu#4]
Some type of indicator on the function that is exposed at the top of the module would be useful.  This is in reference to https://groups.google.com/forum/#!topic/elm-discuss/N_Pd1XsgtwU where they are discussing visibility of the exposed list.  Keeping it at the top is sensible to see them all in one place, but it is also nice to see it at the function declaration too, so some indicator that it is so would be nice (Like color-coding it differently I'd say).

**Comment by halohalospecial** [comment]
@OvermindDL1, this is available in https://atom.io/packages/elm-lens :slightly_smiling_face:
