### ISSUE TITLE
elmjutsu is overriding js-hyperclick with noop

### ISSUE THREAD

**Issue by markogresak** [halohalospecial/atom-elmjutsu#40]
As discussed here: https://github.com/AsaAyers/js-hyperclick/issues/53

Not sure why it's overriding hyperclick in js files. Can this be fixed or at least a way to select where the hyperclick provider should work? I love the package when working with elm, but for now, I'll have to keep it disabled when working in js.

**Comment by AsaAyers** [comment]
Immediately before returning [this promise](https://github.com/halohalospecial/atom-elmjutsu/blob/271fe8731f9a5de72b15ab18334db008ed262a53/lib/hyperclick-provider.js#L10), you need to verify that the code has the right scope for you to scan. It looks like you have that check inside the promise, so it just needs to be moved.

[here](https://github.com/AsaAyers/js-hyperclick/blob/adbc0e21adf77f68adb0d93af430a66af09c5a0a/lib/js-hyperclick.js#L136) is the check js-hyperclick uses to make sure I'm only scanning JavaScript files.

**Comment by halohalospecial** [comment]
@markogresak, @AsaAyers, thanks a lot for debugging this :heart: I was able to replicate the issue by installing `js-hyperclick`.  @AsaAyers, thank you for pointing out the needed fix!  Also, great package!  I'm using it right now :smiley:
