### ISSUE TITLE
Feature Request: Offline support?

### ISSUE THREAD

**Issue by jah2488** [halohalospecial/atom-elmjutsu#47]
Hey!

I love elmjutsu it is really amazing and useful. I also have spotty internet where I live and sometimes find myself hacking on an elm project without any. I've noticed this causes several elmjutsu related features like autocomplete, imports, and the sidekick to not work or provide their same level of utility. They're not broken, they just clearly expect a constant internet connection.

I haven't looked into it, so it may not even be possible to have a local cache of autocomplete definitions and documentation, but it if were an option that'd great.

A half way solution would be someway of forcing a reload or local cache, because I've always run into a few situations where my internet is restored but the sidekick our autocomplete continues to say I'm offline, or there was a connection error, etc.

Thanks again!

**Comment by halohalospecial** [comment]
Hi! You can set `Cache Directory` to a non-temporary directory so that elmjutsu does not need to download 3rd-party docs again when you restart Atom.

**Comment by jah2488** [comment]
@halohalospecial This is great, I didn't realize that. Thanks!
