### ISSUE TITLE
Completion from type annotation should take into account '|>'

### ISSUE THREAD

**Issue by mandrolic** [halohalospecial/atom-elmjutsu#48]
The completion from type annotation is really useful, but when you are piping in the last parameter, you have to just delete that part of the auto completion

[] |> Lists.Extra.Find  (a -> Bool) List a

You don't really want the last 'List a'

Not sure how feasible it is, but would be nice

edit:

Also may be worth looking at some of the other operators like <|, >> << and infix functions

**Comment by halohalospecial** [comment]
Great idea!  Let's add that special case.  Thanks for the suggestion!
