### ISSUE TITLE
Add Import: duplicate existing imports are not always removed

### ISSUE THREAD

**Issue by mandrolic** [halohalospecial/atom-elmjutsu#51]
Given:

```
module Main exposing (..)

import Html
import Array
import List
import List

import List

```
Then Add Import -> Task

Get:

```
module Main exposing (..)

import Array
import Html
import List
import Task

import List

```

Note 'import List' is still there twice
Perhaps the clear line between duplicate 'import List' is stopping the de-duping.

```
module Main exposing (..)

import Html
import Array
import List
import List
import List
```

Seems to work OK.

I think this is another case probably, where the feature works as long as you have elm-formatted code

**Comment by halohalospecial** [comment]
This should be fixed in v3.5.1.  Thanks!
