### ISSUE TITLE
Support non-ASCII names

### ISSUE THREAD

**Issue by jespersm** [halohalospecial/atom-elmjutsu#57]
Elmjutsu doesn't seem to work with "international" letters, i.e. outside the ASCII ranges, even if Elm, Atom and JavaScript support these just fine.

Example:

```
med = " med "

fløde = "fløde"

dessert = "rødgrød" ++ med ++ fløde
```

Hyperclicking on "med" jumps to the definition just fine, but doing the same on "fløde" is a no-op. These should work the same.

**Comment by jespersm** [comment]
Awesome, thanks! I did actually download the code and intend to fix it myself, but wasn't sure I had the rights commands to build the elm/*.js files from their *.elm counterparts. Is there an easy way?

**Comment by halohalospecial** [comment]
I just execute `elm-make Indexer.elm --output=indexer.js` in the command line :grinning:  However, the change I did was in a .js file.
