### ISSUE TITLE
Elm syntax coloring and formatting for blocks.

### ISSUE THREAD

**Issue by OvermindDL1** [halohalospecial/atom-elmjutsu#6]
Elm syntax coloring and formatting for blocks.

As per https://groups.google.com/forum/#!topic/elm-discuss/HIdcbC0IOHk the blocks in Elm, like glsl blocks, are not formatted properly.  It would be nice if they were not only syntax colored properly based on the embedded type (for known blocks like GLSL), but potentially even change the atom language within them (like how Atom's markdown auto-colors code fences properly based on the language).

Example GLSL block in a function:
```elm
fragmentShader : Shader {} Uniform Varying
fragmentShader =
    [glsl|
         precision mediump float;
         varying vec4 fragColor;

         void main () {
             gl_FragColor = fragColor;
         }
    |]
```

**Comment by halohalospecial** [comment]
Hi @OvermindDL1, the [language-elm](https://github.com/edubkendo/atom-elm) package would be a better place for this :-)
