### ISSUE TITLE
Autocompletion of function call whose type contains type variable

### ISSUE THREAD

**Issue by aravantv** [halohalospecial/atom-elmjutsu#60]
Step-by-step:

1. in any source file, type in `Result.m` (really, just 'm')
-> the context menu should display `Result.map` as the first entry
2. press enter to complete your entry into `Result.map`

Observed: `Result.map (a -> value) Result.Result x a` gets inserted into the source code

However would be nicer, in my opinion, to have: `Result.map (a -> value) (Result.Result x a)`

The current behaviour gives the misleading impression that the function has 4 arguments.
It's even more annoying if there are more parameters after the second argument: one really has to think where arguments begin or end.

**Comment by halohalospecial** [comment]
Good idea!  Thanks for the suggestion!

**Comment by halohalospecial** [comment]
This is already in the latest version (v5.1.1).  Thanks!

**Comment by aravantv** [comment]
No way. You're a machine. Thank you!!!
