### ISSUE TITLE
Type Annotation Automation

### ISSUE THREAD

**Issue by stanshillis** [halohalospecial/atom-elmjutsu#61]
Elmjutsu shows inferred type annotation warning very nicely on the bottom. I was wondering if it's possible to have some way of automating the process of putting that type annotation into code. Perhaps by clicking on that warning somewhere, or a keyboard shortcut when text cursor is placed on the function with that warning. It is also not possible to copy that suggested signature from the pop-over tooltip or that panel on the bottom (this on mac osx atom 1.14.2). Having ability to copy it from there would help a lot.

Thanks!

**Comment by halohalospecial** [comment]
Hi!  I think you're referring to the [`linter-elm-make`](https://github.com/mybuddymichael/linter-elm-make) bottom panel/tooltip.  If so, the command you're looking for is [`Linter Elm Make: Quick Fix`](https://github.com/mybuddymichael/linter-elm-make#linter-elm-make-quick-fix).  Here's a related screen capture: https://raw.githubusercontent.com/mybuddymichael/linter-elm-make/master/images/show-inferred-type-annotations.gif

**Comment by halohalospecial** [comment]
If you want to copy anything from the bottom panel, you should use <kbd>Ctrl</kbd>+<kbd>C</kbd> regardless of whether you're using Mac or Windows.  It's a limitation of the `linter` package.  There's relevant discussion here: https://github.com/mybuddymichael/linter-elm-make/issues/63.

**Comment by stanshillis** [comment]
thank you! I apologize for posting the questing in the wrong place.

**Comment by halohalospecial** [comment]
No worries!  It happens all the time :grin:  Maybe because people were used to having Elm plugins that had everything in other (i.e. non-Atom) editors/IDEs.
