### ISSUE TITLE
Add import does not add import

### ISSUE THREAD

**Issue by pacbeckh** [halohalospecial/atom-elmjutsu#65]
Given the following file: 
```
module Foo (selectEventHandler)

import Json.Decode as Json
import Html.Events.Extra exposing (targetSelectedIndex)
import Html.Events exposing (on)


selectEventHandler : (Maybe Int -> msg) -> Html.Attribute msg
selectEventHandler onSelect =
    on "change" (Json.map onSelect targetSelectedIndex)
```

An import is suggested for Html.Attribute. Nothing happens when Add Import is executed:
![ScreenCapture](https://media.giphy.com/media/3o7bugEe7cvObUdG6I/source.gif)

**Comment by halohalospecial** [comment]
@pacbeckh, thanks for the report!

I noticed there's a syntax error:
    `module Foo (selectEventHandler)`
should be
    `module Foo exposing (selectEventHandler)`

When I added " exposing ", `Add Import` worked as usual.  I still have to check why.

**Comment by pacbeckh** [comment]
@halohalospecial that must have happened when copying the code around. 

Strange that it does work on your computer, as it still doesn't work for me even if `exposing` is added (The gif, does have the `exposing` on the right place).

**Comment by pacbeckh** [comment]
I managed to reduce the problem to:

```
module Foo exposing (..)

import Json.Decode
import Html.Events


selectEventHandler : (Maybe Int -> msg) -> Html.Attribute msg
selectEventHandler onSelect =
    Html.Events.on "change" (Json.Decode.fail "")
```

It seems that if `import Html.Events` import is already present, it cannot also add `Html`

Demo:
![ScreenCapture](https://media.giphy.com/media/xUPGchmn2PKS7kc75K/source.gif)

Also tested by @stil4m

**Comment by halohalospecial** [comment]
Hmm, weird that it's working on my computer :thinking:

![add-import-issue](https://cloud.githubusercontent.com/assets/2138906/23899751/503980ea-08f1-11e7-8efc-1da1dd3e598d.gif)

**Comment by halohalospecial** [comment]
Oh!  You're using the `Quick Fix` command of `linter-elm-make`.  It does not have information about the imports.

**Comment by pacbeckh** [comment]
@halohalospecial , it is indeed the `Quick Fix` command.  I should have made that more clear. 

It does work if `import Html.Event` is removed.
