### ISSUE TITLE
Missing settings-menu

### ISSUE THREAD

**Issue by eirikm** [halohalospecial/atom-elmjutsu#74]
Atom 1.15.0 x64 on Mac
elmjutsu 5.5.1

![elmjutsu missing settings](https://cloud.githubusercontent.com/assets/504763/24742798/01569e1e-1aac-11e7-8945-8f7667873944.jpg)

**Comment by halohalospecial** [comment]
Hi @eirikm, I think that is an Atom bug.

You can try to do the following:
1. Uninstall `elmjutsu`.
2. Exit `Atom`.
3. Start `Atom`.
4. Reinstall `elmjutsu`.
5. Exit Atom.
6. Start `Atom`.

**Comment by eirikm** [comment]
I rebuilt the package and now it works.
Thought I should document the process, but now I can't reproduce the error :-/

thanks!

**Comment by halohalospecial** [comment]
It happens from time to time, even with other packages :-)  You can also try the same workaround if you encounter issues after updating a package.

**Comment by earthrid** [comment]
Hi, I had the same problem (under Atom 1.20.1 and 1.21.0-beta, elmjutsu 6.0.0) and with the help of this page + the Atom debugging docs I finally got it. :)

Here's the recipe that worked for me (there's nothing new here, but the sequence might help some other confused person who finds this page).

1) Is there red bug icon in the bottom right of any Atom window? This is the incompatible package indicator. Click on it.

2) Select "Rebuild packages" (ahhh...)

3) Go the Packages section of Atom's settings and uninstall elmjutsu.

4) Restart Atom.

5) Reinstall elmjutsu.

It's easy once you know how! ;D
