### ISSUE TITLE
"Failed to download package docs" warning cannot be disabled.

### ISSUE THREAD

**Issue by rupertlssmith** [halohalospecial/atom-elmjutsu#80]
I am using some packages that are not on http://package.elm-lang.org/, which results in an error pop-up appearing every time I open a .elm file.

It would be nice if there was a way to disable this warning.

**Comment by wende** [comment]
I'm using many packages that aren't there.
I'd love to be able to have elmjutsu working when it cannot reach the pacakges

**Comment by rupertlssmith** [comment]
@wende Lets look at the code and see if we an make a pull request for this - it should just be the case of commenting out a single line?

**Comment by halohalospecial** [comment]
Hi!  Can you check if the latest version (v.5.6.0) satisfies your use cases :smiley_cat:  Thanks!

**Comment by rupertlssmith** [comment]
v 5.6.0 is good for me; the annoying messages are gone. Thanks a lot for sorting it. :-)
