### ISSUE TITLE
bad symbol renaming - the new name of the symbol is duplicated with each renaming

### ISSUE THREAD

**Issue by AionDev** [halohalospecial/atom-elmjutsu#81]
Today i noticed this:
![bad symbol renaming in `elmjutsu` - the name is duplicated](https://user-images.githubusercontent.com/20288140/27978372-bb1203a2-6377-11e7-9ab2-d405674b13ee.gif)

My installed non-default atom packages are:
```
elm-format                -- this is the elm group
elmjutsu
language-elm
linter-elm-make

linter
linter-sass-lint
linter-ui-default

atom-beautify        

busy-signal
color-picker
highlight-selected
intentions
minimap
minimap-highlight-selected

```
I restarted atom, i uninstalled and reinstalled `elmjutsu` again.
What is interesting is that no one reported this issue yet.
My Settings for the `elmjutsu` package are the default ones. - didn't change anything i mean.
![settings1](https://user-images.githubusercontent.com/20288140/27978555-c6666f62-6378-11e7-9e53-2bf366270631.png)
![settings2](https://user-images.githubusercontent.com/20288140/27978556-c8b0752e-6378-11e7-8d66-c68f63b60521.png)
![settings3](https://user-images.githubusercontent.com/20288140/27978559-ca80843e-6378-11e7-85ee-0a6ba0fffb46.png)

Pretty interesting :smile: - couple of days ago - i didn't noticed anything. Seems this issue is recent. Thanks! :smile:

**Comment by halohalospecial** [comment]
Nice catch, @AionDev! :smile:  Looks like it's because elmjutsu detected 2 symbols named `Document` in `type Document = Document { ... }`.
