### ISSUE TITLE
Is integrating elm-lint in scope?

### ISSUE THREAD

**Issue by brasilikum** [halohalospecial/atom-elmjutsu#82]
https://github.com/jfmengels/elm-lint seems to hint to a lot of good practices.
Do you see including this in scope for this package or should someone turn it into a separate package?

**Comment by halohalospecial** [comment]
Hi!  https://github.com/stil4m/elm-analyse, a similar tool, is going to have an Atom package (https://twitter.com/ElmNetherlands/status/875063341575798784).

**Comment by brasilikum** [comment]
Wow! This is cool!
