### ISSUE TITLE
Feature Request:  Sidekick displays doc comments

### ISSUE THREAD

**Issue by OvermindDL1** [halohalospecial/atom-elmjutsu#9]
Documentation comments `{-| doc comment place before function -}` in the current project would be awesome to see in the sidekick.  I have a few functions in one of my modules that I like to see the doc of to see how to format certain parts of the input but the sidekick only displays, for example `SomeApp.SimpleHelpers.flagsContain : List String -> String -> Bool` instead of the documentation comment associated with it as well.

**Comment by halohalospecial** [comment]
It's in the to do list, but low priority.  You can submit a PR haha.

**Comment by OvermindDL1** [comment]
Lol, should I get time for it I would.  ^.^

**Comment by halohalospecial** [comment]
I'm already working on this :-)

**Comment by halohalospecial** [comment]
Added in the latest version (2.5.4.).
