### ISSUE TITLE
Very slow edit/save on large projects 

### ISSUE THREAD

**Issue by anagrius** [halohalospecial/atom-elmjutsu#91]
We have a project 50k+ lines of Elm. We love Elmjutsu! Atm though we can't use it because it makes editing Elm files, very slow when typing and saving.

I profiled a little and it seems that the `getActiveFileTokens` in Indexes is one of the major culprits. We would love to use the addon, but right now, it almost makes Atom unusable event on new machines. I will try to do more profiling to see what is going on.

**Comment by halohalospecial** [comment]
Hi @anagrius, do you think it's because you have lots of files, you have large files, or both?  On my machine, it's tolerable on a 4.2K-line file :smile_cat:

**Comment by halohalospecial** [comment]
Oh, and there are some features that are really slow :sweat_smile: (https://github.com/halohalospecial/atom-elmjutsu#performance-tuning)

**Comment by amitaibu** [comment]
@halohalospecial awesome package!

on my machine I have also https://atom.io/packages/language-elm for the syntax highlight. When I disabled `autocomplete` option of `language-elm` -- elmjitsu became fast again.

**Comment by amitaibu** [comment]
Care for a PR to add this to the README ?

**Comment by halohalospecial** [comment]
Sure @amitaibu :smile: 

There's also this note in the README:

> It's recommended to uncheck Enable autocomplete of the language-elm package to prevent duplicate suggestions.

**Comment by amitaibu** [comment]
Oh, sorry I missed it, I was looking for it in the performance tuning. Maybe worth moving it to a more prominent place -- as it's very likely that most users will have `language-elm` as-well?

**Comment by halohalospecial** [comment]
@amitaibu, I'll add it to the "Performance Tuning" section.  Thanks for the suggestion!

**Comment by halohalospecial** [comment]
@amitaibu, Elmjutsu will offer to disable `language-elm`'s autocomplete in the next version :smile_cat:

![disable-autocomplete](https://user-images.githubusercontent.com/2138906/30575199-bdffe61c-9d31-11e7-8fd5-509452a95e36.png)

**Comment by amitaibu** [comment]
Nice one! 😄
