### ISSUE TITLE
autocomplete suggestions very slow

### ISSUE THREAD

**Issue by haasDev** [halohalospecial/atom-elmjutsu#92]
autocomplete suggestions are currently taking between 10 and 15 seconds before it brings things up.  This happens even in a very small project. Here is a gist of the project. 

https://gist.github.com/anonymous/631271faa044727deccdbfc3c8f92817

I am not sure what I can provide you to get what is needed to solve this issue but let me know and I'll be sure to provide it.  Thanks!

**Comment by halohalospecial** [comment]
@haasDev, here are things you can try to improve performance: https://github.com/halohalospecial/atom-elmjutsu#autocomplete-performance-tuning

Or you can try disabling features one by one until you find out which one is slow :D

**Comment by haasDev** [comment]
disabling autocomplete in language-elm did it!  Thanks!

**Comment by halohalospecial** [comment]
Oh, I see.  Thanks for that info!  In the next version, Elmjutsu will offer to disable autocomplete of `language-elm`.
