### ISSUE TITLE
Respect indentation preference in snippets

### ISSUE THREAD

**Issue by karljs** [halohalospecial/atom-elmjutsu#93]
I don't know if this is a limitation of Atom or not, but it would be great if the snippets you provide respected the indentation preferences set globally in Atom.  For instance, if I choose 2 space indentation in my own personal settings, the Elmjutsu snippets will still indent using 4 spaces.

**Comment by halohalospecial** [comment]
Hi @karljs, Elmjutsu is following elm-format's convention of 4 spaces :slightly_smiling_face:

**Comment by halohalospecial** [comment]
It shouldn't be hard to get the indentation setting from Atom, though :slightly_smiling_face:  I'll see if I can add that to the next release.  Thanks!

**Comment by halohalospecial** [comment]
Looks like the default number of indentation spaces for the Elm grammar is `2`.  If we get the value from the settings, we'll not be following `elm-format`'s convention.  Not sure if `language-elm` can change the default to `4`.

**Comment by OvermindDL1** [comment]
elm-format would reformat it anyway.  Whatever atom uses should match the formatter.

**Comment by karljs** [comment]
I didn't realize `elm-format`specified 4 spaces.  I come mostly from Haskell where 2 spaces seems much more common, but maybe I should try to adjust.  Anyway, thanks for looking in to this and the feedback.
