### ISSUE TITLE
elmjutsu seems to stop looking for elm-package.json at Main.elm folder

### ISSUE THREAD

**Issue by raffomania** [halohalospecial/atom-elmjutsu#96]
My elm files live in a subfolder of my project:
```
├── client
│   ├── Animations.elm
│   ├── Main.elm
│   ├── Messages.elm
│   ├── Model.elm
│   ├── Stylesheets.elm
│   ├── Update.elm
│   └── View.elm
├── elm-package.json
```
elmjutsu is, after updating to 7.0.5, no longer able to find elm-package.json. I'm not sure why, as elm-package.json is definitely in my atom project root. 

I have the same problem with `atom-linter-elm-make`; When telling it to generate `elm-package.json` for me, it creates a new one in the `client` folder, so I suppose both blugins might stop looking after finding `Main.elm`?

**Comment by raffomania** [comment]
Repo in question: https://github.com/Nukesor/spacesurvival

**Comment by raffomania** [comment]
I had a look at the code, the offending line seems to be https://github.com/halohalospecial/atom-elmjutsu/blob/b9727c27485633d3c2dda8a6819689d28f670d24/lib/helper.js#L614

making elmjutsu always stop searching one folder beneath the project root, as `parentDirectory` does not contain a trailing path separator, in comparison to the second argument. A quick fix would be removing the `path.sep` addition at the end of the line, but I don't know why it's there in the first place so maybe that would break something?

**Comment by timjs** [comment]
I have the same problem but reverting to 7.0.2 (which I had installed before) doesn't help. Maybe it is regression in Atom's core from 1.21.1 to 1.21.2? I updated it at the same time.

**Comment by saturday06** [comment]
@timjs downgrading elmjutsu and linter-elm-make works for me.
```
apm uninstall elmjutsu
apm install elmjutsu@7.0.4
apm uninstall linter-elm-make
apm install linter-elm-make@0.26.2
```

**Comment by timjs** [comment]
Works too for me!

**Comment by halohalospecial** [comment]
Sorry, was busy earlier.  I'll publish a fix in a few minutes.

**Comment by halohalospecial** [comment]
Hi!  Can you try elmjutsu v7.0.6 and linter-elm-make v0.27.1?  Thanks!

**Comment by saturday06** [comment]
Both updates work fine for me. Thanks!

**Comment by raffomania** [comment]
Works for me too, thanks for the incredibly fast response!

**Comment by halohalospecial** [comment]
@raffomania, thanks for providing a sample repo!  It was working on my setup :)

**Comment by timjs** [comment]
Works great! Thanks a lot!
