### ISSUE TITLE
Auto-complete blocks return key.

### ISSUE THREAD

**Issue by rupertlssmith** [halohalospecial/atom-elmjutsu#97]
![auto-complete-problem](https://user-images.githubusercontent.com/5537079/32369573-8bcdbffc-c081-11e7-822e-4c120344e8a7.png)

The above image shows me typing and at the end of the line I just typed a '='. Auto-select comes up, but I just want to hit the return key and move to the next line, and accept the '=' character as my auto-select choice. Unfortunately the return key is blocked by the auto complete from performing its normal function.

I think hitting return should accept the current auto-complete choice, and insert a new line as normal.

Driving me nuts; I've disable auto-complete for now.

**Comment by halohalospecial** [comment]
Hi, @rupertlssmith!

It was working like this before:
> I think hitting return should accept the current auto-complete choice, and insert a new line as normal.

.. but a change in the `autocomplete-plus` package some versions ago disabled the workaround (see also #5).

In the meantime, you can change the value of `Autocomplete Min Chars` in the Settings view to `2`.  I'm still looking for a proper way to solve this issue.

Thanks!

**Comment by rupertlssmith** [comment]
Thanks for the work-around, I'll try that.

**Comment by halohalospecial** [comment]
@rupertlssmith, this should be fixed in the latest version (v7.1.0) :)
