### ISSUE TITLE
Can't copy from linter in MacOS

### ISSUE THREAD

**Issue by simonh1000** [halohalospecial/atom-elmjutsu#99]
In Linux I can do 

 - alt-A and it inserts a type declaration automatically for me
 - copy infered types from the linter info and paste into my code

Neither are possible in MacOS. alt-a does not do anything, and copy pasting seems to add some weird hidden characters that the compiler then rejects

![screen shot 2017-11-07 at 20 01 20](https://user-images.githubusercontent.com/5256724/32512178-7f34cab0-c3f6-11e7-8ff0-a911a61f17cb.png)

**Comment by halohalospecial** [comment]
Hi @simonh1000, the feature is from linter-elm-make :smile: <kbd>alt-a</kbd> in Linux is for the `Diagnostics: Show Actions At Position` command (if you installed `nuclide` or `atom-ide-ui`).  I don't know what's the equivalent for MacOS.  You can try typing the command name in the command palette to check the keybinding for that.

**Comment by simonh1000** [comment]
I suspected i might end re-directed, but thanks so much for the comprehensive answer
